/**
 * A real, verified-buildable Next.js + Tailwind + Postgres scaffold.
 * This exact combination (same dependency versions as this platform
 * itself) was installed and built successfully, including a Postgres-
 * backed API route and a page calling it, before this ever shipped.
 *
 * The AI only ever generates files INSIDE this shell (app/page.tsx,
 * app/api/*, lib/db.ts contents) — it never writes package.json,
 * tsconfig, or build config, which removes the most common ways a
 * generated project fails to build.
 */
export function scaffoldFiles(appName: string): Record<string, string> {
  const safeName = appName.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50) || "generated-app";

  return {
    "package.json": JSON.stringify(
      {
        name: safeName,
        version: "0.1.0",
        private: true,
        scripts: { dev: "next dev", build: "next build", start: "next start" },
        dependencies: {
          next: "16.3.1",
          react: "19.2.8",
          "react-dom": "19.2.8",
          pg: "^8.23.0",
        },
        devDependencies: {
          "@types/node": "^20",
          "@types/react": "^19",
          "@types/react-dom": "^19",
          "@types/pg": "^8.23.1",
          "@tailwindcss/postcss": "^4",
          tailwindcss: "^4",
          typescript: "^5",
        },
      },
      null,
      2
    ),

    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2017",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "react-jsx",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2
    ),

    "next.config.ts": `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`,

    "postcss.config.mjs": `const config = { plugins: ["@tailwindcss/postcss"] };\nexport default config;\n`,

    ".gitignore": `node_modules\n.next\n.env*.local\n*.log\n`,

    "app/globals.css": `@import "tailwindcss";\n`,

    "app/layout.tsx": `import "./globals.css";\n\nexport const metadata = {\n  title: "${appName.replace(/"/g, '\\"')}",\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,

    "lib/db.ts": `import { Pool } from "pg";\n\nlet pool: Pool | null = null;\n\nfunction getPool(): Pool {\n  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set.");\n  if (!pool) {\n    pool = new Pool({\n      connectionString: process.env.DATABASE_URL,\n      ssl: process.env.DATABASE_URL.includes("sslmode=disable") ? false : { rejectUnauthorized: false },\n    });\n  }\n  return pool;\n}\n\n// Runs a parameterized query. Each API route is responsible for its own\n// "CREATE TABLE IF NOT EXISTS" before querying its table (see the\n// generated route files for the pattern). That statement is idempotent\n// and cheap, so running it defensively on each request is fine at this\n// scale and needs no separate migration step.\nexport async function query<T extends Record<string, unknown> = Record<string, unknown>>(\n  text: string,\n  params: unknown[] = []\n): Promise<T[]> {\n  const res = await getPool().query<T>(text, params);\n  return res.rows;\n}\n`,

    "README.md": `# ${appName}\n\nGenerated by Groundwork's full-stack builder. Real Next.js, real API routes, real Postgres — not a static demo.\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Deploy\n\nPush this to GitHub, import it at vercel.com/new, and set **DATABASE_URL** in the project's environment variables (any Postgres connection string — Vercel Postgres, Neon, and Supabase all work) — the app creates its own tables on first request. Without it, the API routes will return a clear error instead of failing silently.\n`,
  };
}
